# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MeffDialog
                                 A QGIS plugin
 This plugin computes mesh effective size
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-05
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Mathieu Chailloux
        email                : mathieu@chailloux.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from .steps import params, landuse, fragm,  reporting

class FragScapeModel:

    def __init__(self):
        self.paramsModel = params.ParamsModel(self)
        self.landuseModel = landuse.LanduseModel(self)
        self.fragmModel = fragm.FragmModel(self)
        self.reportingModel = reporting.ReportingModel(self)
        self.parser_name = "FragScapeModel"
        
    def checkWorkspaceInit(self):
        self.paramsModel.checkWorkspaceInit()
            
    # Returns relative path w.r.t. workspace directory.
    # File separator is set to common slash '/'.
    def normalizePath(self,path):
        return self.paramsModel.normalizePath(path)
            
    # Returns absolute path from normalized path (cf 'normalizePath' function)
    def getOrigPath(self,path):
        return self.paramsModel.getOrigPath(path)
    
    def mkOutputFile(self,name):
        return self.paramsModel.mkOutputFile(name)
        
    def toXML(self,indent=""):
        xmlStr = indent + "<" + self.parser_name
        new_indent = " "
        if self.paramsModel:
            xmlstr += self.paramsModel.toXML(indent=new_indent)
        if self.landuseModel:
            xmlstr += self.landuseModel.toXML(indent=new_indent)
        if self.fragmModel:
            xmlstr += self.fragmModel.toXML(indent=new_indent)
        if self.reportingModel:
            xmlstr += self.reportingModel.toXML(indent=new_indent)
        xmlStr += indent + "</" + self.parser_name + ">"
        
    def fromXMLRoot(self,infile):
        self.paramsModel.fromXML()
        self.landuseModel.fromXML()
        self.fragmModel.fromXML()
        self.reportingModel.fromXML()
        
    