# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FragScape_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FragScapeDialogBase(object):
    def setupUi(self, FragScapeDialogBase):
        FragScapeDialogBase.setObjectName("FragScapeDialogBase")
        FragScapeDialogBase.resize(1015, 690)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FragScapeDialogBase.sizePolicy().hasHeightForWidth())
        FragScapeDialogBase.setSizePolicy(sizePolicy)
        self.gridLayout_22 = QtWidgets.QGridLayout(FragScapeDialogBase)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.frame = QtWidgets.QFrame(FragScapeDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(3, 0, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.scrollArea = QgsScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 580))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 767, 671))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.langFr = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/frFlag.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.langFr.setIcon(icon)
        self.langFr.setCheckable(True)
        self.langFr.setChecked(True)
        self.langFr.setAutoRaise(True)
        self.langFr.setObjectName("langFr")
        self.gridLayout_6.addWidget(self.langFr, 0, 6, 1, 1)
        self.saveProjectAs = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveProjectAs.sizePolicy().hasHeightForWidth())
        self.saveProjectAs.setSizePolicy(sizePolicy)
        self.saveProjectAs.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/mActionFileSaveAs.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveProjectAs.setIcon(icon1)
        self.saveProjectAs.setAutoRaise(True)
        self.saveProjectAs.setObjectName("saveProjectAs")
        self.gridLayout_6.addWidget(self.saveProjectAs, 0, 1, 1, 1)
        self.saveProject = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveProject.sizePolicy().hasHeightForWidth())
        self.saveProject.setSizePolicy(sizePolicy)
        self.saveProject.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/mActionFileSave.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveProject.setIcon(icon2)
        self.saveProject.setAutoRaise(True)
        self.saveProject.setObjectName("saveProject")
        self.gridLayout_6.addWidget(self.saveProject, 0, 2, 1, 1)
        self.langEn = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.langEn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/enFlag.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.langEn.setIcon(icon3)
        self.langEn.setCheckable(True)
        self.langEn.setAutoRaise(True)
        self.langEn.setObjectName("langEn")
        self.gridLayout_6.addWidget(self.langEn, 0, 5, 1, 1)
        self.openProject = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openProject.sizePolicy().hasHeightForWidth())
        self.openProject.setSizePolicy(sizePolicy)
        self.openProject.setMinimumSize(QtCore.QSize(0, 0))
        self.openProject.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/mActionFileOpen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openProject.setIcon(icon4)
        self.openProject.setAutoRaise(True)
        self.openProject.setObjectName("openProject")
        self.gridLayout_6.addWidget(self.openProject, 0, 0, 1, 1)
        self.aboutButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.aboutButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/iconHelpConsole.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutButton.setIcon(icon5)
        self.aboutButton.setAutoRaise(True)
        self.aboutButton.setObjectName("aboutButton")
        self.gridLayout_6.addWidget(self.aboutButton, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(790, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 4, 1, 1)
        self.mTabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mTabWidget.sizePolicy().hasHeightForWidth())
        self.mTabWidget.setSizePolicy(sizePolicy)
        self.mTabWidget.setMinimumSize(QtCore.QSize(550, 550))
        self.mTabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mTabWidget.setObjectName("mTabWidget")
        self.paramsTab = QtWidgets.QWidget()
        self.paramsTab.setObjectName("paramsTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.paramsTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.paramsTab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_15.addWidget(self.label_11, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.paramlabel = QtWidgets.QLabel(self.paramsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramlabel.sizePolicy().hasHeightForWidth())
        self.paramlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.paramlabel.setFont(font)
        self.paramlabel.setObjectName("paramlabel")
        self.verticalLayout.addWidget(self.paramlabel)
        self.paramsFrame = QtWidgets.QFrame(self.paramsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsFrame.sizePolicy().hasHeightForWidth())
        self.paramsFrame.setSizePolicy(sizePolicy)
        self.paramsFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.paramsFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.paramsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.paramsFrame.setObjectName("paramsFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.paramsFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.workspaceLabel = QtWidgets.QLabel(self.paramsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workspaceLabel.sizePolicy().hasHeightForWidth())
        self.workspaceLabel.setSizePolicy(sizePolicy)
        self.workspaceLabel.setObjectName("workspaceLabel")
        self.gridLayout.addWidget(self.workspaceLabel, 0, 0, 1, 1)
        self.saveTmpResultsFlag = QtWidgets.QCheckBox(self.paramsFrame)
        self.saveTmpResultsFlag.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saveTmpResultsFlag.setText("")
        self.saveTmpResultsFlag.setChecked(True)
        self.saveTmpResultsFlag.setObjectName("saveTmpResultsFlag")
        self.gridLayout.addWidget(self.saveTmpResultsFlag, 2, 1, 1, 1)
        self.workspace = gui.QgsFileWidget(self.paramsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workspace.sizePolicy().hasHeightForWidth())
        self.workspace.setSizePolicy(sizePolicy)
        self.workspace.setObjectName("workspace")
        self.gridLayout.addWidget(self.workspace, 0, 1, 1, 1)
        self.boundsLayer_3 = QtWidgets.QLabel(self.paramsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boundsLayer_3.sizePolicy().hasHeightForWidth())
        self.boundsLayer_3.setSizePolicy(sizePolicy)
        self.boundsLayer_3.setObjectName("boundsLayer_3")
        self.gridLayout.addWidget(self.boundsLayer_3, 2, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.paramsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 3, 0, 1, 1)
        self.paramsCrs = gui.QgsProjectionSelectionWidget(self.paramsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsCrs.sizePolicy().hasHeightForWidth())
        self.paramsCrs.setSizePolicy(sizePolicy)
        self.paramsCrs.setObjectName("paramsCrs")
        self.gridLayout.addWidget(self.paramsCrs, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.paramsFrame)
        self.paramsView = QtWidgets.QTableView(self.paramsTab)
        self.paramsView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsView.sizePolicy().hasHeightForWidth())
        self.paramsView.setSizePolicy(sizePolicy)
        self.paramsView.setMinimumSize(QtCore.QSize(0, 120))
        self.paramsView.setMaximumSize(QtCore.QSize(16777215, 120))
        self.paramsView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.paramsView.setDragEnabled(False)
        self.paramsView.setAlternatingRowColors(False)
        self.paramsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.paramsView.setSortingEnabled(False)
        self.paramsView.setObjectName("paramsView")
        self.verticalLayout.addWidget(self.paramsView)
        spacerItem1 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.mTabWidget.addTab(self.paramsTab, "")
        self.landuseTab = QtWidgets.QWidget()
        self.landuseTab.setObjectName("landuseTab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.landuseTab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_3 = QtWidgets.QLabel(self.landuseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 0, 0, 1, 1)
        self.selectionLayerFrame_2 = QtWidgets.QFrame(self.landuseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerFrame_2.sizePolicy().hasHeightForWidth())
        self.selectionLayerFrame_2.setSizePolicy(sizePolicy)
        self.selectionLayerFrame_2.setMinimumSize(QtCore.QSize(200, 110))
        self.selectionLayerFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.selectionLayerFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectionLayerFrame_2.setObjectName("selectionLayerFrame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.selectionLayerFrame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.selectionLayerLabel_3 = QtWidgets.QLabel(self.selectionLayerFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_3.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_3.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_3.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionLayerLabel_3.setFont(font)
        self.selectionLayerLabel_3.setObjectName("selectionLayerLabel_3")
        self.gridLayout_5.addWidget(self.selectionLayerLabel_3, 0, 0, 1, 1)
        self.selectionLayerLabel_6 = QtWidgets.QLabel(self.selectionLayerFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_6.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_6.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_6.setMinimumSize(QtCore.QSize(138, 16))
        self.selectionLayerLabel_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectionLayerLabel_6.setObjectName("selectionLayerLabel_6")
        self.gridLayout_5.addWidget(self.selectionLayerLabel_6, 1, 0, 1, 1)
        self.landuseInputLayerCombo = gui.QgsMapLayerComboBox(self.selectionLayerFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landuseInputLayerCombo.sizePolicy().hasHeightForWidth())
        self.landuseInputLayerCombo.setSizePolicy(sizePolicy)
        self.landuseInputLayerCombo.setMinimumSize(QtCore.QSize(0, 0))
        self.landuseInputLayerCombo.setObjectName("landuseInputLayerCombo")
        self.gridLayout_5.addWidget(self.landuseInputLayerCombo, 1, 1, 1, 1)
        self.landuseInputLayer = QtWidgets.QToolButton(self.selectionLayerFrame_2)
        self.landuseInputLayer.setObjectName("landuseInputLayer")
        self.gridLayout_5.addWidget(self.landuseInputLayer, 1, 2, 1, 1)
        self.selectionLayerLabel_14 = QtWidgets.QLabel(self.selectionLayerFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_14.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_14.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_14.setMinimumSize(QtCore.QSize(138, 16))
        self.selectionLayerLabel_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectionLayerLabel_14.setObjectName("selectionLayerLabel_14")
        self.gridLayout_5.addWidget(self.selectionLayerLabel_14, 2, 0, 1, 1)
        self.landuseClipDataFlag = QtWidgets.QCheckBox(self.selectionLayerFrame_2)
        self.landuseClipDataFlag.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.landuseClipDataFlag.setText("")
        self.landuseClipDataFlag.setChecked(False)
        self.landuseClipDataFlag.setObjectName("landuseClipDataFlag")
        self.gridLayout_5.addWidget(self.landuseClipDataFlag, 2, 1, 1, 1)
        self.selectionLayerLabel_15 = QtWidgets.QLabel(self.selectionLayerFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_15.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_15.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_15.setMinimumSize(QtCore.QSize(138, 16))
        self.selectionLayerLabel_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectionLayerLabel_15.setObjectName("selectionLayerLabel_15")
        self.gridLayout_5.addWidget(self.selectionLayerLabel_15, 3, 0, 1, 1)
        self.landuseClipLayer = gui.QgsFileWidget(self.selectionLayerFrame_2)
        self.landuseClipLayer.setEnabled(False)
        self.landuseClipLayer.setObjectName("landuseClipLayer")
        self.gridLayout_5.addWidget(self.landuseClipLayer, 3, 1, 1, 2)
        self.gridLayout_11.addWidget(self.selectionLayerFrame_2, 1, 0, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.landuseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy)
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_24)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_11 = QtWidgets.QFrame(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(200)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.landuseRun = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landuseRun.sizePolicy().hasHeightForWidth())
        self.landuseRun.setSizePolicy(sizePolicy)
        self.landuseRun.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.landuseRun.setIcon(icon6)
        self.landuseRun.setObjectName("landuseRun")
        self.horizontalLayout_11.addWidget(self.landuseRun)
        self.gridLayout_10.addWidget(self.frame_11, 3, 0, 1, 2)
        self.landuseSelectionMode = QtWidgets.QComboBox(self.frame_24)
        self.landuseSelectionMode.setObjectName("landuseSelectionMode")
        self.landuseSelectionMode.addItem("")
        self.landuseSelectionMode.addItem("")
        self.gridLayout_10.addWidget(self.landuseSelectionMode, 1, 1, 1, 1)
        self.selectionLayerLabel_9 = QtWidgets.QLabel(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_9.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_9.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_9.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionLayerLabel_9.setFont(font)
        self.selectionLayerLabel_9.setObjectName("selectionLayerLabel_9")
        self.gridLayout_10.addWidget(self.selectionLayerLabel_9, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 1, 0, 1, 1)
        self.landuseSelectionStack = QtWidgets.QStackedWidget(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landuseSelectionStack.sizePolicy().hasHeightForWidth())
        self.landuseSelectionStack.setSizePolicy(sizePolicy)
        self.landuseSelectionStack.setObjectName("landuseSelectionStack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.landuseSelectField = gui.QgsFieldComboBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landuseSelectField.sizePolicy().hasHeightForWidth())
        self.landuseSelectField.setSizePolicy(sizePolicy)
        self.landuseSelectField.setObjectName("landuseSelectField")
        self.gridLayout_7.addWidget(self.landuseSelectField, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 1, 0, 1, 1)
        self.landuseDescrField = gui.QgsFieldComboBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landuseDescrField.sizePolicy().hasHeightForWidth())
        self.landuseDescrField.setSizePolicy(sizePolicy)
        self.landuseDescrField.setAllowEmptyFieldName(True)
        self.landuseDescrField.setObjectName("landuseDescrField")
        self.gridLayout_7.addWidget(self.landuseDescrField, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 24))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.landuseLoadFields = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landuseLoadFields.sizePolicy().hasHeightForWidth())
        self.landuseLoadFields.setSizePolicy(sizePolicy)
        self.landuseLoadFields.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/mActionRefresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.landuseLoadFields.setIcon(icon7)
        self.landuseLoadFields.setObjectName("landuseLoadFields")
        self.horizontalLayout.addWidget(self.landuseLoadFields)
        self.gridLayout_7.addWidget(self.frame_3, 2, 0, 1, 2)
        self.landuseView = QtWidgets.QTableView(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landuseView.sizePolicy().hasHeightForWidth())
        self.landuseView.setSizePolicy(sizePolicy)
        self.landuseView.setMinimumSize(QtCore.QSize(300, 100))
        self.landuseView.setAlternatingRowColors(True)
        self.landuseView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.landuseView.setSortingEnabled(True)
        self.landuseView.setObjectName("landuseView")
        self.gridLayout_7.addWidget(self.landuseView, 3, 0, 1, 2)
        self.landuseRemove = QtWidgets.QToolButton(self.page)
        self.landuseRemove.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/mActionDeleteSelected.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.landuseRemove.setIcon(icon8)
        self.landuseRemove.setAutoRaise(True)
        self.landuseRemove.setObjectName("landuseRemove")
        self.gridLayout_7.addWidget(self.landuseRemove, 4, 0, 1, 1)
        self.landuseSelectionStack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.selectionOpenLayerLabel_6 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionOpenLayerLabel_6.sizePolicy().hasHeightForWidth())
        self.selectionOpenLayerLabel_6.setSizePolicy(sizePolicy)
        self.selectionOpenLayerLabel_6.setMinimumSize(QtCore.QSize(67, 16))
        self.selectionOpenLayerLabel_6.setObjectName("selectionOpenLayerLabel_6")
        self.gridLayout_12.addWidget(self.selectionOpenLayerLabel_6, 0, 0, 1, 1)
        self.landuseSelectExpr = gui.QgsFieldExpressionWidget(self.page_2)
        self.landuseSelectExpr.setObjectName("landuseSelectExpr")
        self.gridLayout_12.addWidget(self.landuseSelectExpr, 0, 1, 1, 1)
        self.landuseSelectionStack.addWidget(self.page_2)
        self.gridLayout_10.addWidget(self.landuseSelectionStack, 2, 0, 1, 2)
        self.gridLayout_11.addWidget(self.frame_24, 2, 0, 1, 1)
        self.mTabWidget.addTab(self.landuseTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_4 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_14.addWidget(self.label_4, 0, 0, 1, 1)
        self.selectionLayerFrame_3 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerFrame_3.sizePolicy().hasHeightForWidth())
        self.selectionLayerFrame_3.setSizePolicy(sizePolicy)
        self.selectionLayerFrame_3.setMinimumSize(QtCore.QSize(200, 110))
        self.selectionLayerFrame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.selectionLayerFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectionLayerFrame_3.setObjectName("selectionLayerFrame_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.selectionLayerFrame_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.selectionLayerLabel_4 = QtWidgets.QLabel(self.selectionLayerFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_4.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_4.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_4.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionLayerLabel_4.setFont(font)
        self.selectionLayerLabel_4.setObjectName("selectionLayerLabel_4")
        self.gridLayout_13.addWidget(self.selectionLayerLabel_4, 0, 0, 1, 1)
        self.selectionLayerLabel_7 = QtWidgets.QLabel(self.selectionLayerFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_7.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_7.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_7.setMinimumSize(QtCore.QSize(0, 16))
        self.selectionLayerLabel_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectionLayerLabel_7.setObjectName("selectionLayerLabel_7")
        self.gridLayout_13.addWidget(self.selectionLayerLabel_7, 1, 0, 1, 1)
        self.fragmInputLayerCombo = gui.QgsMapLayerComboBox(self.selectionLayerFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fragmInputLayerCombo.sizePolicy().hasHeightForWidth())
        self.fragmInputLayerCombo.setSizePolicy(sizePolicy)
        self.fragmInputLayerCombo.setMinimumSize(QtCore.QSize(0, 0))
        self.fragmInputLayerCombo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fragmInputLayerCombo.setObjectName("fragmInputLayerCombo")
        self.gridLayout_13.addWidget(self.fragmInputLayerCombo, 1, 1, 1, 1)
        self.fragmInputLayer = QtWidgets.QToolButton(self.selectionLayerFrame_3)
        self.fragmInputLayer.setObjectName("fragmInputLayer")
        self.gridLayout_13.addWidget(self.fragmInputLayer, 1, 2, 1, 1)
        self.selectionLayerLabel_17 = QtWidgets.QLabel(self.selectionLayerFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_17.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_17.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_17.setMinimumSize(QtCore.QSize(138, 16))
        self.selectionLayerLabel_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectionLayerLabel_17.setObjectName("selectionLayerLabel_17")
        self.gridLayout_13.addWidget(self.selectionLayerLabel_17, 2, 0, 1, 1)
        self.fragmClipDataFlag = QtWidgets.QCheckBox(self.selectionLayerFrame_3)
        self.fragmClipDataFlag.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fragmClipDataFlag.setText("")
        self.fragmClipDataFlag.setChecked(False)
        self.fragmClipDataFlag.setObjectName("fragmClipDataFlag")
        self.gridLayout_13.addWidget(self.fragmClipDataFlag, 2, 1, 1, 1)
        self.selectionLayerLabel_16 = QtWidgets.QLabel(self.selectionLayerFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_16.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_16.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_16.setMinimumSize(QtCore.QSize(138, 16))
        self.selectionLayerLabel_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectionLayerLabel_16.setObjectName("selectionLayerLabel_16")
        self.gridLayout_13.addWidget(self.selectionLayerLabel_16, 3, 0, 1, 1)
        self.fragmClipLayer = gui.QgsFileWidget(self.selectionLayerFrame_3)
        self.fragmClipLayer.setEnabled(False)
        self.fragmClipLayer.setMinimumSize(QtCore.QSize(0, 0))
        self.fragmClipLayer.setObjectName("fragmClipLayer")
        self.gridLayout_13.addWidget(self.fragmClipLayer, 3, 1, 1, 2)
        self.gridLayout_14.addWidget(self.selectionLayerFrame_3, 1, 0, 1, 1)
        self.frame_23 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_23)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.selectionLayerLabel_8 = QtWidgets.QLabel(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_8.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_8.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_8.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionLayerLabel_8.setFont(font)
        self.selectionLayerLabel_8.setObjectName("selectionLayerLabel_8")
        self.gridLayout_4.addWidget(self.selectionLayerLabel_8, 0, 0, 1, 1)
        self.fragmExprLabel = QtWidgets.QLabel(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fragmExprLabel.sizePolicy().hasHeightForWidth())
        self.fragmExprLabel.setSizePolicy(sizePolicy)
        self.fragmExprLabel.setMinimumSize(QtCore.QSize(52, 13))
        font = QtGui.QFont()
        font.setItalic(True)
        self.fragmExprLabel.setFont(font)
        self.fragmExprLabel.setObjectName("fragmExprLabel")
        self.gridLayout_4.addWidget(self.fragmExprLabel, 1, 0, 1, 1)
        self.fragmBufferLabel = QtWidgets.QLabel(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fragmBufferLabel.sizePolicy().hasHeightForWidth())
        self.fragmBufferLabel.setSizePolicy(sizePolicy)
        self.fragmBufferLabel.setMinimumSize(QtCore.QSize(52, 13))
        self.fragmBufferLabel.setObjectName("fragmBufferLabel")
        self.gridLayout_4.addWidget(self.fragmBufferLabel, 2, 0, 1, 1)
        self.fragmExpr = gui.QgsFieldExpressionWidget(self.frame_23)
        self.fragmExpr.setMinimumSize(QtCore.QSize(0, 0))
        self.fragmExpr.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fragmExpr.setObjectName("fragmExpr")
        self.gridLayout_4.addWidget(self.fragmExpr, 1, 1, 1, 1)
        self.fragmName = QtWidgets.QLineEdit(self.frame_23)
        self.fragmName.setMinimumSize(QtCore.QSize(0, 0))
        self.fragmName.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fragmName.setObjectName("fragmName")
        self.gridLayout_4.addWidget(self.fragmName, 3, 1, 1, 1)
        self.fragmBuffer = gui.QgsFieldExpressionWidget(self.frame_23)
        self.fragmBuffer.setMinimumSize(QtCore.QSize(0, 0))
        self.fragmBuffer.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fragmBuffer.setObjectName("fragmBuffer")
        self.gridLayout_4.addWidget(self.fragmBuffer, 2, 1, 1, 1)
        self.fragmIsFragm = QtWidgets.QLabel(self.frame_23)
        self.fragmIsFragm.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fragmIsFragm.sizePolicy().hasHeightForWidth())
        self.fragmIsFragm.setSizePolicy(sizePolicy)
        self.fragmIsFragm.setMinimumSize(QtCore.QSize(52, 13))
        self.fragmIsFragm.setObjectName("fragmIsFragm")
        self.gridLayout_4.addWidget(self.fragmIsFragm, 4, 0, 1, 1)
        self.fragmCheckbox = QtWidgets.QCheckBox(self.frame_23)
        self.fragmCheckbox.setEnabled(False)
        self.fragmCheckbox.setText("")
        self.fragmCheckbox.setCheckable(True)
        self.fragmCheckbox.setChecked(True)
        self.fragmCheckbox.setObjectName("fragmCheckbox")
        self.gridLayout_4.addWidget(self.fragmCheckbox, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_23)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame_23, 2, 0, 1, 1)
        self.selectionViewFrame_2 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionViewFrame_2.sizePolicy().hasHeightForWidth())
        self.selectionViewFrame_2.setSizePolicy(sizePolicy)
        self.selectionViewFrame_2.setMinimumSize(QtCore.QSize(350, 200))
        self.selectionViewFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.selectionViewFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectionViewFrame_2.setObjectName("selectionViewFrame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.selectionViewFrame_2)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_12 = QtWidgets.QFrame(self.selectionViewFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 9)
        self.horizontalLayout_12.setSpacing(200)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.fragmAdd = QtWidgets.QPushButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fragmAdd.sizePolicy().hasHeightForWidth())
        self.fragmAdd.setSizePolicy(sizePolicy)
        self.fragmAdd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fragmAdd.setIcon(icon2)
        self.fragmAdd.setObjectName("fragmAdd")
        self.horizontalLayout_12.addWidget(self.fragmAdd)
        self.gridLayout_2.addWidget(self.frame_12, 0, 1, 1, 1)
        self.fragmView = QtWidgets.QTableView(self.selectionViewFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fragmView.sizePolicy().hasHeightForWidth())
        self.fragmView.setSizePolicy(sizePolicy)
        self.fragmView.setMinimumSize(QtCore.QSize(300, 100))
        self.fragmView.setAlternatingRowColors(True)
        self.fragmView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fragmView.setSortingEnabled(True)
        self.fragmView.setObjectName("fragmView")
        self.gridLayout_2.addWidget(self.fragmView, 1, 0, 1, 2)
        self.fragmRemove = QtWidgets.QToolButton(self.selectionViewFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fragmRemove.sizePolicy().hasHeightForWidth())
        self.fragmRemove.setSizePolicy(sizePolicy)
        self.fragmRemove.setText("")
        self.fragmRemove.setIcon(icon8)
        self.fragmRemove.setAutoRaise(True)
        self.fragmRemove.setObjectName("fragmRemove")
        self.gridLayout_2.addWidget(self.fragmRemove, 2, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.selectionViewFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(200)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.fragmRun = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fragmRun.sizePolicy().hasHeightForWidth())
        self.fragmRun.setSizePolicy(sizePolicy)
        self.fragmRun.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fragmRun.setIcon(icon6)
        self.fragmRun.setObjectName("fragmRun")
        self.horizontalLayout_10.addWidget(self.fragmRun)
        self.gridLayout_2.addWidget(self.frame_9, 3, 1, 1, 1)
        self.gridLayout_14.addWidget(self.selectionViewFrame_2, 3, 0, 1, 1)
        self.mTabWidget.addTab(self.tab, "")
        self.fusionTab = QtWidgets.QWidget()
        self.fusionTab.setObjectName("fusionTab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.fusionTab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_8 = QtWidgets.QLabel(self.fusionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 0, 1, 1)
        self.selectionLayerFrame_4 = QtWidgets.QFrame(self.fusionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerFrame_4.sizePolicy().hasHeightForWidth())
        self.selectionLayerFrame_4.setSizePolicy(sizePolicy)
        self.selectionLayerFrame_4.setMinimumSize(QtCore.QSize(200, 65))
        self.selectionLayerFrame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.selectionLayerFrame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectionLayerFrame_4.setObjectName("selectionLayerFrame_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.selectionLayerFrame_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.selectionLayerLabel_5 = QtWidgets.QLabel(self.selectionLayerFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_5.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_5.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_5.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.selectionLayerLabel_5.setFont(font)
        self.selectionLayerLabel_5.setObjectName("selectionLayerLabel_5")
        self.gridLayout_8.addWidget(self.selectionLayerLabel_5, 0, 0, 1, 1)
        self.resultsInputLayer = gui.QgsMapLayerComboBox(self.selectionLayerFrame_4)
        self.resultsInputLayer.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsInputLayer.sizePolicy().hasHeightForWidth())
        self.resultsInputLayer.setSizePolicy(sizePolicy)
        self.resultsInputLayer.setMinimumSize(QtCore.QSize(60, 20))
        self.resultsInputLayer.setMaximumSize(QtCore.QSize(16777215, 16))
        self.resultsInputLayer.setAllowEmptyLayer(True)
        self.resultsInputLayer.setObjectName("resultsInputLayer")
        self.gridLayout_8.addWidget(self.resultsInputLayer, 0, 1, 1, 1)
        self.selectionLayerLabel_10 = QtWidgets.QLabel(self.selectionLayerFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_10.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_10.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_10.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.selectionLayerLabel_10.setFont(font)
        self.selectionLayerLabel_10.setObjectName("selectionLayerLabel_10")
        self.gridLayout_8.addWidget(self.selectionLayerLabel_10, 1, 0, 1, 1)
        self.resultsSelection = gui.QgsFieldExpressionWidget(self.selectionLayerFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsSelection.sizePolicy().hasHeightForWidth())
        self.resultsSelection.setSizePolicy(sizePolicy)
        self.resultsSelection.setMinimumSize(QtCore.QSize(0, 20))
        self.resultsSelection.setObjectName("resultsSelection")
        self.gridLayout_8.addWidget(self.resultsSelection, 1, 1, 1, 1)
        self.selectionLayerLabel_12 = QtWidgets.QLabel(self.selectionLayerFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_12.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_12.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_12.setMinimumSize(QtCore.QSize(120, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.selectionLayerLabel_12.setFont(font)
        self.selectionLayerLabel_12.setObjectName("selectionLayerLabel_12")
        self.gridLayout_8.addWidget(self.selectionLayerLabel_12, 2, 0, 1, 1)
        self.resultsReportingLayer = gui.QgsFileWidget(self.selectionLayerFrame_4)
        self.resultsReportingLayer.setMinimumSize(QtCore.QSize(0, 20))
        self.resultsReportingLayer.setObjectName("resultsReportingLayer")
        self.gridLayout_8.addWidget(self.resultsReportingLayer, 2, 1, 1, 1)
        self.selectionLayerLabel_13 = QtWidgets.QLabel(self.selectionLayerFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_13.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_13.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_13.setMinimumSize(QtCore.QSize(120, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.selectionLayerLabel_13.setFont(font)
        self.selectionLayerLabel_13.setObjectName("selectionLayerLabel_13")
        self.gridLayout_8.addWidget(self.selectionLayerLabel_13, 3, 0, 1, 1)
        self.resultsCutMode = QtWidgets.QComboBox(self.selectionLayerFrame_4)
        self.resultsCutMode.setObjectName("resultsCutMode")
        self.resultsCutMode.addItem("")
        self.resultsCutMode.addItem("")
        self.gridLayout_8.addWidget(self.resultsCutMode, 3, 1, 1, 1)
        self.selectionLayerLabel_11 = QtWidgets.QLabel(self.selectionLayerFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_11.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_11.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_11.setMinimumSize(QtCore.QSize(80, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.selectionLayerLabel_11.setFont(font)
        self.selectionLayerLabel_11.setObjectName("selectionLayerLabel_11")
        self.gridLayout_8.addWidget(self.selectionLayerLabel_11, 4, 0, 1, 1)
        self.resultsOutLayer = gui.QgsFileWidget(self.selectionLayerFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsOutLayer.sizePolicy().hasHeightForWidth())
        self.resultsOutLayer.setSizePolicy(sizePolicy)
        self.resultsOutLayer.setMinimumSize(QtCore.QSize(100, 20))
        self.resultsOutLayer.setMaximumSize(QtCore.QSize(16777215, 16))
        self.resultsOutLayer.setAccessibleName("")
        self.resultsOutLayer.setAccessibleDescription("")
        self.resultsOutLayer.setDialogTitle("")
        self.resultsOutLayer.setDefaultRoot("")
        self.resultsOutLayer.setObjectName("resultsOutLayer")
        self.gridLayout_8.addWidget(self.resultsOutLayer, 4, 1, 1, 1)
        self.selectionLayerLabel_18 = QtWidgets.QLabel(self.selectionLayerFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionLayerLabel_18.sizePolicy().hasHeightForWidth())
        self.selectionLayerLabel_18.setSizePolicy(sizePolicy)
        self.selectionLayerLabel_18.setMinimumSize(QtCore.QSize(120, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.selectionLayerLabel_18.setFont(font)
        self.selectionLayerLabel_18.setObjectName("selectionLayerLabel_18")
        self.gridLayout_8.addWidget(self.selectionLayerLabel_18, 5, 0, 1, 1)
        self.resultsUnit = QtWidgets.QComboBox(self.selectionLayerFrame_4)
        self.resultsUnit.setObjectName("resultsUnit")
        self.resultsUnit.addItem("")
        self.resultsUnit.addItem("")
        self.resultsUnit.addItem("")
        self.resultsUnit.addItem("")
        self.gridLayout_8.addWidget(self.resultsUnit, 5, 1, 1, 1)
        self.gridLayout_9.addWidget(self.selectionLayerFrame_4, 1, 0, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 2, 0, 1, 1)
        self.resultsRun = QtWidgets.QPushButton(self.fusionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsRun.sizePolicy().hasHeightForWidth())
        self.resultsRun.setSizePolicy(sizePolicy)
        self.resultsRun.setMinimumSize(QtCore.QSize(0, 24))
        self.resultsRun.setMaximumSize(QtCore.QSize(16777215, 24))
        self.resultsRun.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resultsRun.setIcon(icon6)
        self.resultsRun.setObjectName("resultsRun")
        self.gridLayout_9.addWidget(self.resultsRun, 2, 1, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 2, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(122, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.fusionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 3, 1, 1, 1)
        self.resultsGlobalRes = QtWidgets.QLineEdit(self.fusionTab)
        self.resultsGlobalRes.setReadOnly(True)
        self.resultsGlobalRes.setObjectName("resultsGlobalRes")
        self.gridLayout_9.addWidget(self.resultsGlobalRes, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.fusionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 3, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(122, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 3, 4, 1, 1)
        self.resultsView = QtWidgets.QTableView(self.fusionTab)
        self.resultsView.setSortingEnabled(True)
        self.resultsView.setWordWrap(False)
        self.resultsView.setObjectName("resultsView")
        self.gridLayout_9.addWidget(self.resultsView, 4, 0, 1, 5)
        self.mTabWidget.addTab(self.fusionTab, "")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.logTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txtLog = QtWidgets.QTextEdit(self.logTab)
        self.txtLog.setReadOnly(True)
        self.txtLog.setObjectName("txtLog")
        self.verticalLayout_3.addWidget(self.txtLog)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.debugButton = QtWidgets.QToolButton(self.logTab)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/debug_icon/mActionAnnotation.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.debugButton.setIcon(icon9)
        self.debugButton.setCheckable(True)
        self.debugButton.setAutoRaise(True)
        self.debugButton.setObjectName("debugButton")
        self.horizontalLayout_2.addWidget(self.debugButton)
        self.logSaveAs = QtWidgets.QToolButton(self.logTab)
        self.logSaveAs.setIcon(icon1)
        self.logSaveAs.setAutoRaise(True)
        self.logSaveAs.setObjectName("logSaveAs")
        self.horizontalLayout_2.addWidget(self.logSaveAs)
        self.logClear = QtWidgets.QToolButton(self.logTab)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/iconClearConsole.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logClear.setIcon(icon10)
        self.logClear.setAutoRaise(True)
        self.logClear.setObjectName("logClear")
        self.horizontalLayout_2.addWidget(self.logClear)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.mTabWidget.addTab(self.logTab, "")
        self.gridLayout_6.addWidget(self.mTabWidget, 1, 0, 1, 7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.textShortHelp = QtWidgets.QTextBrowser(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textShortHelp.sizePolicy().hasHeightForWidth())
        self.textShortHelp.setSizePolicy(sizePolicy)
        self.textShortHelp.setMinimumSize(QtCore.QSize(200, 0))
        self.textShortHelp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textShortHelp.setAccessibleName("")
        self.textShortHelp.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textShortHelp.setOpenLinks(False)
        self.textShortHelp.setObjectName("textShortHelp")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.frame, 0, 0, 1, 2)
        self.lblProgress = QtWidgets.QLabel(FragScapeDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProgress.sizePolicy().hasHeightForWidth())
        self.lblProgress.setSizePolicy(sizePolicy)
        self.lblProgress.setText("")
        self.lblProgress.setWordWrap(True)
        self.lblProgress.setObjectName("lblProgress")
        self.gridLayout_22.addWidget(self.lblProgress, 1, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(FragScapeDialogBase)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(61, 61))
        self.label_2.setMaximumSize(QtCore.QSize(61, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/logoIrstea.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.frame_10)
        self.label.setMinimumSize(QtCore.QSize(122, 61))
        self.label.setMaximumSize(QtCore.QSize(122, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/plugins/FragScape/icons/logoTetis.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.gridLayout_22.addWidget(self.frame_10, 1, 1, 2, 1)
        self.progressBar = QtWidgets.QProgressBar(FragScapeDialogBase)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_22.addWidget(self.progressBar, 2, 0, 1, 1)

        self.retranslateUi(FragScapeDialogBase)
        self.mTabWidget.setCurrentIndex(0)
        self.landuseSelectionStack.setCurrentIndex(0)
        self.resultsInputLayer.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(FragScapeDialogBase)

    def retranslateUi(self, FragScapeDialogBase):
        _translate = QtCore.QCoreApplication.translate
        FragScapeDialogBase.setWindowTitle(_translate("FragScapeDialogBase", "FragScape - Landscape fragmentation"))
        self.langFr.setText(_translate("FragScapeDialogBase", "..."))
        self.saveProjectAs.setToolTip(_translate("FragScapeDialogBase", "Enregistrer le projet FragScape sous"))
        self.saveProject.setToolTip(_translate("FragScapeDialogBase", "Enregistrer le projet FragScape"))
        self.langEn.setToolTip(_translate("FragScapeDialogBase", "English"))
        self.openProject.setToolTip(_translate("FragScapeDialogBase", "Ouvrir un projet FragScape"))
        self.aboutButton.setToolTip(_translate("FragScapeDialogBase", "À propos"))
        self.label_11.setText(_translate("FragScapeDialogBase", "<html><head/><body><p>Bienvenue dans FragScape 1.0 !</p><p>Ce plugin permet de calculer la taille effective de maille d\'un territoire depuis les données d\'entrée vectorielles (occupation du sol, éléments fragmentants) en 4 étapes :<br/>1) Définition des paramètres généraux<br/>2) Sélection des éléments non fragmentants de l\'occupation du sol<br/>3) Intégration des éléments fragmentants<br/>4) Calcul des indicateurs de fragmentation</p><p><span style=\" font-weight:600;\">Pensez à sauvegarder régulièrement la configuration du plugin (boutons </span><img src=\":/plugins/FragScape/icons/mActionFileSaveAs.svg\"/><span style=\" font-weight:600;\">, </span><img src=\":/plugins/FragScape/icons/mActionFileSave.svg\"/><span style=\" font-weight:600;\"> en haut à gauche de l\'interface).</span></p><p>Page web : <a href=\"https://www.umr-tetis.fr/index.php/fr/production/donnees-et-plateformes/plateformes/426-fragscape\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.umr-tetis.fr/index.php/fr/production/donnees-et-plateformes/plateformes/426-fragscape</span></a><br/></p></body></html>"))
        self.paramlabel.setText(_translate("FragScapeDialogBase", "Paramètres globaux"))
        self.workspaceLabel.setText(_translate("FragScapeDialogBase", "Dossier de travail"))
        self.workspace.setToolTip(_translate("FragScapeDialogBase", "<html><head/><body><p><span style=\" font-weight:600;\">Dossier de travail</span></p><p>Contient les couches produites par FragScape. Les chemins relatifs sont construits à partir ce dossier.</p></body></html>"))
        self.boundsLayer_3.setText(_translate("FragScapeDialogBase", "Sauver les couches intermédiaires"))
        self.label_47.setText(_translate("FragScapeDialogBase", "Projection"))
        self.mTabWidget.setTabText(self.mTabWidget.indexOf(self.paramsTab), _translate("FragScapeDialogBase", "1 - Paramètres"))
        self.label_3.setText(_translate("FragScapeDialogBase", "Occupation du sol"))
        self.selectionLayerLabel_3.setText(_translate("FragScapeDialogBase", "1 - Couche d\'entrée"))
        self.selectionLayerLabel_6.setText(_translate("FragScapeDialogBase", "Couche d\'entrée"))
        self.landuseInputLayer.setText(_translate("FragScapeDialogBase", "..."))
        self.selectionLayerLabel_14.setText(_translate("FragScapeDialogBase", "Couper les données d\'entrée"))
        self.selectionLayerLabel_15.setText(_translate("FragScapeDialogBase", "Couche de découpage"))
        self.landuseRun.setText(_translate("FragScapeDialogBase", "Lancer la sélection"))
        self.landuseSelectionMode.setItemText(0, _translate("FragScapeDialogBase", "Par valeur de champ"))
        self.landuseSelectionMode.setItemText(1, _translate("FragScapeDialogBase", "Par expression"))
        self.selectionLayerLabel_9.setText(_translate("FragScapeDialogBase", "2 - Sélection"))
        self.label_9.setText(_translate("FragScapeDialogBase", "Mode de sélection"))
        self.label_5.setText(_translate("FragScapeDialogBase", "Champ de selection"))
        self.label_7.setText(_translate("FragScapeDialogBase", "Champ de description [optionnel]"))
        self.landuseLoadFields.setText(_translate("FragScapeDialogBase", "Afficher les valeurs de champ"))
        self.selectionOpenLayerLabel_6.setText(_translate("FragScapeDialogBase", "Expression"))
        self.mTabWidget.setTabText(self.mTabWidget.indexOf(self.landuseTab), _translate("FragScapeDialogBase", "2 - Occupation du sol"))
        self.label_4.setText(_translate("FragScapeDialogBase", "Éléments fragmentants"))
        self.selectionLayerLabel_4.setText(_translate("FragScapeDialogBase", "1 - Couche d\'entrée"))
        self.selectionLayerLabel_7.setText(_translate("FragScapeDialogBase", "Couche d\'entrée"))
        self.fragmInputLayer.setText(_translate("FragScapeDialogBase", "..."))
        self.selectionLayerLabel_17.setText(_translate("FragScapeDialogBase", "Couper les données d\'entrée"))
        self.selectionLayerLabel_16.setText(_translate("FragScapeDialogBase", "Couche de découpage"))
        self.selectionLayerLabel_8.setText(_translate("FragScapeDialogBase", "2 - Sélection"))
        self.fragmExprLabel.setText(_translate("FragScapeDialogBase", "Expression [opt.]"))
        self.fragmBufferLabel.setText(_translate("FragScapeDialogBase", "Tampon"))
        self.fragmIsFragm.setText(_translate("FragScapeDialogBase", "Sélection fragmentante"))
        self.label_6.setText(_translate("FragScapeDialogBase", "Identifiant"))
        self.fragmAdd.setText(_translate("FragScapeDialogBase", "Enregistrer la sélection"))
        self.fragmRemove.setToolTip(_translate("FragScapeDialogBase", "Supprimer les lignes sélectionnées"))
        self.fragmRun.setText(_translate("FragScapeDialogBase", "Intégrer les éléments fragmentants"))
        self.mTabWidget.setTabText(self.mTabWidget.indexOf(self.tab), _translate("FragScapeDialogBase", "3 - Éléments fragmentants"))
        self.label_8.setText(_translate("FragScapeDialogBase", "Résultats"))
        self.selectionLayerLabel_5.setText(_translate("FragScapeDialogBase", "Couche d\'entrée"))
        self.selectionLayerLabel_10.setText(_translate("FragScapeDialogBase", "Filtrer les patchs [opt.]"))
        self.selectionLayerLabel_12.setText(_translate("FragScapeDialogBase", "Couche de rapportage"))
        self.selectionLayerLabel_13.setText(_translate("FragScapeDialogBase", "Méthode de découpage"))
        self.resultsCutMode.setItemText(0, _translate("FragScapeDialogBase", "CUT (Cutting-Out)"))
        self.resultsCutMode.setItemText(1, _translate("FragScapeDialogBase", "CBC (Cross-Boundary Connection)"))
        self.selectionLayerLabel_11.setText(_translate("FragScapeDialogBase", "Couche de sortie [opt.]"))
        self.selectionLayerLabel_18.setText(_translate("FragScapeDialogBase", "Unité de surface"))
        self.resultsUnit.setItemText(0, _translate("FragScapeDialogBase", "m² (mètres carrés)"))
        self.resultsUnit.setItemText(1, _translate("FragScapeDialogBase", "dm² (décimètres carrés / ares)"))
        self.resultsUnit.setItemText(2, _translate("FragScapeDialogBase", "hm² (hectomètres carrés / hectares)"))
        self.resultsUnit.setItemText(3, _translate("FragScapeDialogBase", "km² (kilomètres carrés)"))
        self.resultsRun.setText(_translate("FragScapeDialogBase", "Calculer les indicateurs"))
        self.label_10.setText(_translate("FragScapeDialogBase", "Taille effective de maille globale"))
        self.mTabWidget.setTabText(self.mTabWidget.indexOf(self.fusionTab), _translate("FragScapeDialogBase", "4 - Résultats"))
        self.debugButton.setToolTip(_translate("FragScapeDialogBase", "Activer le mode debug"))
        self.debugButton.setText(_translate("FragScapeDialogBase", "..."))
        self.logSaveAs.setToolTip(_translate("FragScapeDialogBase", "Enregistrer le journal sous"))
        self.logSaveAs.setText(_translate("FragScapeDialogBase", "..."))
        self.logClear.setToolTip(_translate("FragScapeDialogBase", "Effacer le journal"))
        self.logClear.setText(_translate("FragScapeDialogBase", "..."))
        self.mTabWidget.setTabText(self.mTabWidget.indexOf(self.logTab), _translate("FragScapeDialogBase", "Journal"))
        self.textShortHelp.setHtml(_translate("FragScapeDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Nom étape</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\">Description générale</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Ceci est une description générale</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\">Description détaillée</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">  </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-style:italic;\">param1</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> : description du param 1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">  </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-style:italic;\">param2</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> : description du param 2</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Ceci est un test</span></p></body></html>"))
        self.label_2.setToolTip(_translate("FragScapeDialogBase", "http://www.irstea.fr"))

from qgis import gui
from qgis.gui import QgsScrollArea
